MiniSocial_Project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('accounts/', include(('accounts.urls', 'accounts'), namespace='accounts')),
    path('', include('core.urls'), name='core'),
    path('', include('social.urls'), name='social'),
    path('notifications/', include('notifications.urls'), name='notifications'),
    path('messaging/', include('messaging.urls'), name='messaging'),
    path('requests/', include('requests.urls'), name='requests'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path, reverse_lazy
from . import views

app_name = 'accounts'

urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('register/', views.register_view, name='register'),
    path('profile/', views.profile_view, name='profile'),
    path('profile/edit/', views.profile_edit_view, name='profile_edit'),
    path('password/change/', views.password_change_view, name='password_change'),
    path('users/', views.user_list, name='user_list'),
    path('users/<str:nickname>/', views.public_profile, name='public_profile'),
    path('users/<str:nickname>/follow/', views.toggle_follow, name='toggle_follow'),
    path('password_reset/',
         auth_views.PasswordResetView.as_view(
             template_name='accounts/password_reset_form.html',
             email_template_name='accounts/password_reset_email.html',
             success_url=reverse_lazy('accounts:password_reset_done')  # ✅ явно указано с namespace
         ),
         name='password_reset'
         ),
    path('password_reset/done/',
         auth_views.PasswordResetDoneView.as_view(template_name='accounts/password_reset_done.html',
                                                  ),
         name='password_reset_done'),
    path('reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name='accounts/password_reset_confirm.html',
                                                     success_url=reverse_lazy('accounts:password_reset_complete'), ),
         name='password_reset_confirm'),
    path('reset/done/',
         auth_views.PasswordResetCompleteView.as_view(template_name='accounts/password_reset_complete.html'),
         name='password_reset_complete'),
    path('confirm-email/<uidb64>/<token>/', views.confirm_email, name='confirm_email'),
    path('resend_activation/', views.resend_activation_email, name='resend_activation'),
    path('settings/', views.edit_user_settings, name='edit_user_settings'),

]

core/urls.py
from django.urls import path
from . import views

app_name = 'core'

urlpatterns = [
    path('', views.home, name='home'),
]

messaging/urls.py
from django.urls import path
from . import views

app_name = "messaging"

urlpatterns = [
    path("", views.thread_list, name="thread_list"),
    path("<int:pk>/", views.thread_detail, name="thread_detail"),
    path("start/<str:nickname>/", views.start_thread, name="start_thread"),
]

social/urls.py
#social/urls.py
from django.urls import path
from . import views

app_name = 'social'

urlpatterns = [
    path('posts/', views.post_list, name='post_list'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<int:pk>/edit/', views.post_edit, name='post_edit'),
    path('<int:pk>/', views.post_detail, name='post_detail'),
    path('posts/<int:post_id>/delete/', views.post_delete, name='post_delete'),
    path('<int:pk>/like/', views.post_like_toggle, name='post_like_toggle'),
    path('comments/<int:comment_id>/delete/', views.comment_delete, name='comment_delete'),
]

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm,PasswordChangeForm

from .models import CustomUser, UserSetting

class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = CustomUser
        fields = [
            'username', 'email', 'nickname','first_name', 'last_name',
            'avatar', 'date_of_birth', 'website',
            'telegram', 'whatsapp', 'viber',
            'password1', 'password2'
        ]
        widgets = {
            'username': forms.TextInput(attrs={'class': 'form-control'}),
            'email': forms.EmailInput(attrs={'class': 'form-control'}),
            'nickname': forms.TextInput(attrs={'class': 'form-control'}),
            'first_name': forms.TextInput(attrs={'class': 'form-control'}),
            'last_name': forms.TextInput(attrs={'class': 'form-control'}),
            'avatar': forms.ClearableFileInput(attrs={'class': 'form-control'}),
            'date_of_birth': forms.DateInput(attrs={'class': 'form-control', 'type': 'date'}),
            'website': forms.URLInput(attrs={'class': 'form-control'}),
            'telegram': forms.TextInput(attrs={'class': 'form-control'}),
            'whatsapp': forms.TextInput(attrs={'class': 'form-control'}),
            'viber': forms.TextInput(attrs={'class': 'form-control'}),
            'password1': forms.PasswordInput(attrs={'class': 'form-control'}),
            'password2': forms.PasswordInput(attrs={'class': 'form-control'}),
        }

    def save(self, commit=True):
        user = super().save(commit=False)
        # можно сохранить дополнительные поля позже в профиль, если реализовать связь
        if commit:
            user.save()
        return user

class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = CustomUser
        fields = [
            'first_name', 'last_name', 'email',
            'avatar', 'bio', 'status_message',
            'location', 'website', 'date_of_birth',
            'telegram', 'whatsapp', 'viber',
        ]
        widgets = {
            'first_name': forms.TextInput(attrs={'class': 'form-control'}),
            'last_name': forms.TextInput(attrs={'class': 'form-control'}),
            'email': forms.EmailInput(attrs={'class': 'form-control'}),
            'avatar': forms.ClearableFileInput(attrs={'class': 'form-control'}),
            'bio': forms.Textarea(attrs={'class': 'form-control', 'rows': 3}),
            'status_message': forms.TextInput(attrs={'class': 'form-control'}),
            'location': forms.TextInput(attrs={'class': 'form-control'}),
            'website': forms.URLInput(attrs={'class': 'form-control'}),
            'date_of_birth': forms.DateInput(attrs={'class': 'form-control', 'type': 'date'}),
            'telegram': forms.TextInput(attrs={'class': 'form-control'}),
            'whatsapp': forms.TextInput(attrs={'class': 'form-control'}),
            'viber': forms.TextInput(attrs={'class': 'form-control'}),
        }


class CustomPasswordChangeForm(PasswordChangeForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs.update({
                'class': 'form-control',
                'placeholder': field.label
            })


class UserSettingsForm(forms.ModelForm):
    class Meta:
        model = UserSetting
        fields = ['name', 'value']
        widgets = {
            'name': forms.HiddenInput(),  # имя параметра мы не даем менять
        }

# Если хотим редактировать несколько настроек за раз
class MultipleUserSettingsForm(forms.Form):
    chat_refresh_interval = forms.IntegerField(
        label="Интервал обновления чата (мс)",
        min_value=1000,
        max_value=60000,
        step_size=1000,
    )
    posts_per_page = forms.IntegerField(
        label="Количество постов на странице",
        min_value=5,
        max_value=100,
    )

    def save(self, user):
        from .models import UserSetting
        settings_map = {
            'CHAT_REFRESH_INTERVAL': self.cleaned_data['chat_refresh_interval'],
            'POSTS_PER_PAGE': self.cleaned_data['posts_per_page'],
        }
        for name, value in settings_map.items():
            UserSetting.objects.update_or_create(
                user=user, name=name, defaults={'value': str(value)}
            )

accounts/views.py
# accounts/views.py
from django.conf import settings
from django.contrib import messages
from django.contrib.auth import login, logout, get_user_model, update_session_auth_hash
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.tokens import default_token_generator
from django.core.mail import send_mail
from django.core.paginator import Paginator
from django.db.models import Q
from django.http import JsonResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.template.loader import render_to_string
from django.urls import reverse
from django.utils.encoding import force_bytes
from django.utils.http import urlsafe_base64_decode, urlsafe_base64_encode
from django.views.decorators.http import require_POST

from .forms import CustomUserCreationForm
from .forms import ProfileUpdateForm, CustomPasswordChangeForm, MultipleUserSettingsForm
from .models import CustomUser, UserSetting
from social.models import Post
from utils.notifications import create_notification
from utils.templatetags.rights import can_edit_post
from utils.settings import get_user_settings

User = get_user_model()


def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            login(request, form.get_user())
            return redirect('social:post_list')
    else:
        form = AuthenticationForm()
    return render(request, 'accounts/login.html', {'form': form})


def logout_view(request):
    if request.method == 'POST':
        logout(request)
        return redirect('accounts:login')
    return render(request, 'accounts/logout_confirm.html')


def register_view(request):
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST, request.FILES)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('social:post_list')
    else:
        form = CustomUserCreationForm()
    return render(request, 'accounts/register.html', {'form': form})


@login_required
def profile_view(request):
    posts = Post.objects.filter(author=request.user).order_by('-created_at')
    return render(request, 'accounts/profile.html', {
        'user': request.user,
        'posts': posts,
    })


@login_required
def profile_edit_view(request):
    if request.method == 'POST':
        form = ProfileUpdateForm(request.POST, request.FILES, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect('accounts:profile')
    else:
        form = ProfileUpdateForm(instance=request.user)
    return render(request, 'accounts/profile_edit.html', {'form': form})


@login_required
def password_change_view(request):
    if request.method == 'POST':
        form = CustomPasswordChangeForm(user=request.user, data=request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)
            return redirect('accounts:profile')
    else:
        form = CustomPasswordChangeForm(user=request.user)
    return render(request, 'accounts/password_change.html', {'form': form})



def user_list(request):
    query = request.GET.get('q', '')
    users = User.objects.filter(is_active=True).order_by('nickname')

    if query:
        users = users.filter(
            Q(nickname__icontains=query) | Q(first_name__icontains=query) | Q(last_name__icontains=query)
        )
    posts_per_page = get_user_settings(['POSTS_PER_PAGE'], request.user).get('POSTS_PER_PAGE', 10)
    paginator = Paginator(users, posts_per_page)  # по 10 пользователей на страницу
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    return render(
        request,
        'accounts/user_list.html',
        {'page_obj': page_obj, 'query': query}
    )


def public_profile(request, nickname):
    user_profile = get_object_or_404(User, nickname=nickname)
    posts = user_profile.posts.all()
    followers_count = user_profile.followers.count()
    following_count = user_profile.following.count()
    return render(request, 'accounts/public_profile.html', {
        'profile_user': user_profile,
        'posts': posts,
        'followers_count': followers_count,
        'following_count': following_count,
    })


@login_required
@require_POST
def toggle_follow(request, nickname):
    if request.user.nickname == nickname:
        return JsonResponse({'success': False, 'error': 'Нельзя подписаться на самого себя.'})

    try:
        target_user = get_object_or_404(CustomUser, nickname=nickname)
        print(f'Пользователь {target_user} найден. {request.user} {request.user.following.all()}')  # Добавляем эту строку для отладки (можно удалить, если не нужно)target_user)
    except:
        return JsonResponse({'success': False, 'error': 'Пользователь не найден.'})

    if target_user in request.user.following.all():
        request.user.following.remove(target_user)
        is_following = False
    else:
        request.user.following.add(target_user)
        create_notification(actor=request.user, recipient=target_user, verb='follow')
        is_following = True

    response = JsonResponse({'success': True, 'is_following': is_following})
    return response


def confirm_email(request, uidb64, token):
    try:
        uid = urlsafe_base64_decode(uidb64).decode()
        user = User.objects.get(pk=uid)
    except (TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None

    if user and default_token_generator.check_token(user, token):
        user.is_email_confirmed = True
        user.save()
        messages.success(request, 'Email подтвержден. Теперь вы можете пользоваться всеми функциями.')
    else:
        messages.error(request, 'Ссылка подтверждения недействительна или устарела.')

    return redirect('accounts:login')


@login_required
def resend_activation_email(request):
    user = request.user
    if user.is_email_confirmed:
        messages.info(request, 'Email уже подтвержден.')
        return redirect('accounts:profile')

    token = default_token_generator.make_token(user)
    uid = urlsafe_base64_encode(force_bytes(user.pk))
    activation_link = request.build_absolute_uri(
        reverse('accounts:confirm_email', kwargs={'uidb64': uid, 'token': token})
    )

    subject = 'Подтверждение Email'
    message = render_to_string('accounts/email_confirmation_email.html', {
        'user': user,
        'activation_link': activation_link,
    })

    send_mail(subject, message, settings.DEFAULT_FROM_EMAIL, [user.email])
    messages.success(request, 'Письмо с подтверждением отправлено на вашу почту.')
    return redirect('accounts:profile')

@login_required
def edit_user_settings(request):
    current_values = get_user_settings(['CHAT_REFRESH_INTERVAL', 'POSTS_PER_PAGE'], request.user)
    if request.method == 'POST':
        form = MultipleUserSettingsForm(request.POST)
        if form.is_valid():
            form.save(request.user)
            messages.success(request, "Настройки сохранены")
            return redirect('accounts:edit_user_settings')
    else:
        form = MultipleUserSettingsForm(initial={
            'chat_refresh_interval': current_values['CHAT_REFRESH_INTERVAL'],
            'posts_per_page': current_values['POSTS_PER_PAGE'],
        })
    return render(request, 'accounts/edit_user_settings.html', {'form': form})

accounts/templates/accounts/edit_user_settings.html
<!-- accounts/templates/accounts/edit_user_settings.html -->
{% extends "base.html" %}
{% block title %}Настройки{% endblock %}
{% block content %}
<div class="container mt-4">
    <h3>Настройки пользователя</h3>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="btn btn-primary">Сохранить</button>
    </form>
</div>
{% endblock %}

accounts/templates/accounts/email_confirmation_email.html
{% autoescape off %}
Привет, {{ user.nickname }}!

Вы зарегистрировались на {{ site_name }}.
Пожалуйста, подтвердите ваш email, перейдя по ссылке ниже:

{{ activation_link }}

Если вы не регистрировались — проигнорируйте это письмо.
{% endautoescape %}

accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% block title %}Вход{% endblock %}

{% block content %}
<div class="row justify-content-center">
  <div class="col-md-6">
    <h3 class="mb-4">Вход</h3>
    <form method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit" class="btn btn-primary">Войти</button>
      <a class="btn btn-primary" href="{% url 'accounts:password_reset' %}">Забыли пароль?</a>
    </form>
  </div>
</div>
{% endblock %}

accounts/templates/accounts/password_reset_email.html
{% load i18n %}{% autoescape off %}
{% blocktranslate %}Вы получили это письмо, потому что запросили сброс пароля для вашей учетной записи на сайте {{ site_name }}.{% endblocktranslate %}

{% translate "Пожалуйста, перейдите по ссылке ниже и установите новый пароль:" %}
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'accounts:password_reset_confirm' uidb64=uid token=token %}
{% endblock %}

{% translate 'Ваш логин:' %} {{ user.get_username }}

{% translate "Спасибо, что используете наш сайт!" %}

{% blocktranslate %}Команда {{ site_name }}{% endblocktranslate %}
{% endautoescape %}

accounts/templates/accounts/profile.html
{% extends 'base.html' %}
{% load rights %}
{% block title %}Профиль{% endblock %}
{% block content %}
    <div class="container mt-4">
        <div class="row">
            <div class="col-md-4 text-center">
                {% if user.avatar %}
                    <img src="{{ user.avatar.url }}" class="img-thumbnail rounded-circle mb-3" width="200" height="200">
                {% else %}
                    <i class="fs-1 bi bi-person-square"></i>
                {% endif %}
                <h4>{{ user.get_full_name|default:user.nickname }}</h4>
                {% if user.status_message %}
                    <p class="text-muted">{{ user.status_message }}</p>
                {% endif %}
                {% if user.is_superuser %}
                    <a href="{% url 'admin:index' %}" class="btn btn-outline-dark btn-sm">Админ-панель</a>
                {% endif %}

            </div>

            <div class="col-md-8">
                <h5 class="mb-3">Информация</h5>
                <ul class="list-group list-group-flush mb-3">
                    {% if user.email %}
                        <li class="list-group-item"><strong>Email:</strong> {{ user.email }}</li>
                    {% endif %}
                    {% if user.website %}
                        <li class="list-group-item"><strong>Веб-сайт:</strong> <a href="{{ user.website }}"
                                                                                  target="_blank">{{
                                user.website }}</a></li>
                    {% endif %}
                    {% if user.location %}
                        <li class="list-group-item"><strong>Местоположение:</strong> {{ user.location }}</li>
                    {% endif %}
                    {% if user.date_of_birth %}
                        <li class="list-group-item"><strong>Дата
                            рождения:</strong> {{ user.date_of_birth|date:"d.m.Y" }}</li>
                    {% endif %}
                </ul>

                {% if user.bio %}
                    <h5 class="mb-2">О себе</h5>
                    <p>{{ user.bio|linebreaks }}</p>
                {% endif %}

                {% if user.telegram or user.whatsapp or user.viber %}
                    <h5 class="mt-4">Мессенджеры</h5>
                    <ul class="list-group list-group-flush">
                        {% if user.telegram %}
                            <li class="list-group-item"><strong>Telegram:</strong> @{{ user.telegram }}</li>
                        {% endif %}
                        {% if user.whatsapp %}
                            <li class="list-group-item"><strong>WhatsApp:</strong> {{ user.whatsapp }}</li>
                        {% endif %}
                        {% if user.viber %}
                            <li class="list-group-item"><strong>Viber:</strong> {{ user.viber }}</li>
                        {% endif %}
                    </ul>
                {% endif %}
            </div>
        </div>
        {% if posts %}
            <hr class="my-5">
            <h4>Ваши посты</h4>
            {% for post in posts %}
                <div class="card mb-3">
                    <div class="card-header d-flex justify-content-between">
                        <h5>{{ post.title }}</h5>
                        <small class="text-muted">{{ post.created_at|date:"d.m.Y H:i" }}</small>
                    </div>
                    <div class="card-body">
                        <p>{{ post.content|linebreaks|truncatechars:200 }}</p>
                        {% if post.image %}
                            <img src="{{ post.image.url }}" class="img-fluid rounded" alt="Изображение">
                        {% endif %}
{#                        {% if post|can_edit_post:user %}#}
{#                            <div class="mt-2">#}
{#                                <a href="{% url 'social:post_edit' post.pk %}"#}
{#                                   class="btn btn-sm btn-outline-secondary">Редактировать</a>#}
{#                            </div>#}
{#                        {% endif %}#}
                    </div>
                    <div class="card-footer text-muted d-flex flex-column flex-sm-row justify-content-between gap-2">
                        <div class="d-flex flex-column flex-sm-row justify-content-between gap-1">
                            {% if user|can_interact %}
                                <form class="like-form" data-post-id="{{ post.pk }}" method="post"
                                      action="{% url 'social:post_like_toggle' post.pk %}">
                                    {% csrf_token %}
                                    <button type="submit"
                                            class="like-button btn btn-sm {% if user in post.likes.all %}btn-danger{% else %}btn-outline-danger{% endif %}">
                                        ❤ <span class="like-count">{{ post.likes.count }}</span>
                                    </button>
                                </form>
                            {% else %}
                                ❤ {{ post.likes.count }}
                            {% endif %}
                            &nbsp;&nbsp; 💬 {{ post.comments.count }}&nbsp;&nbsp;&nbsp;&nbsp;
                            <div>
                                <a href="{% url 'social:post_detail' post.pk %}" class="btn btn-sm btn-outline-primary">Подробнее</a>
                            </div>
                            {% if post|can_edit_post:user and user|can_interact %}
                                <div>
                                    <a href="{% url 'social:post_edit' post.pk %}"
                                       class="btn btn-sm btn-outline-secondary">Редактировать</a>
                                </div>
                            {% endif %}
                        </div>
                        <div>
                            {% if post.author %}
                                Автор:
                                <a href="{% url 'accounts:public_profile' post.author.nickname %}">{{ post.author.nickname }}</a>
                            {% else %}
                                <span class="text-muted">Автор удалён</span>
                            {% endif %}
                        </div>
                    </div>
                </div>
            {% empty %}
                <p>Вы пока не опубликовали ни одного поста.</p>
            {% endfor %}
        {% endif %}
    </div>
{% endblock %}

accounts/templates/accounts/public_profile.html
{% extends 'base.html' %}
{% load rights %}
{% block content %}
    <div class="container">
        <h2>{{ profile_user.nickname }}</h2>
        {% if profile_user.avatar %}
            <img src="{{ profile_user.avatar.url }}" alt="Avatar" class="img-thumbnail mb-2" style="max-width: 150px;">
        {% endif %}
        <p><strong>Имя:</strong> {{ profile_user.first_name }} {{ profile_user.last_name }}</p>
        <p><strong>Сейчас:</strong> {{ profile_user.status_message }}</p>
        <p><strong>О себе:</strong> {{ profile_user.bio }}</p>
        <p><strong>Зарегистрирован:</strong> {{ profile_user.date_joined|date:"d.m.Y" }}</p>
        <p>
            Подписчиков: {{ followers_count }}<br>
            Подписок: {{ following_count }}
        </p>
        {% if user.is_authenticated and user != profile_user and user|can_interact %}
            <a href="{% url 'messaging:start_thread' user.nickname %}" class="btn btn-sm btn-outline-secondary"
               title="Написать сообщение">
                <i class="bi bi-envelope"></i>
            </a>
            <form action="{% url 'accounts:toggle_follow' profile_user.nickname %}"
                  method="post"
                  class="ajax-follow-toggle ajax-follow-reload d-inline">
                {% csrf_token %}
                <button type="submit"
                        class="btn btn-sm {% if profile_user in request.user.following.all %}btn-primary{% else %}btn-outline-primary{% endif %}">
                    {% if profile_user in request.user.following.all %}Отписаться{% else %}Подписаться{% endif %}
                </button>
            </form>

        {% endif %}
        <hr>
        <div class="row mt-4">
            <div class="col-md-6">
                <div class="card mb-3">
                    <div class="card-header">
                        Подписчики ({{ followers_count }})
                    </div>
                    <ul class="list-group list-group-flush">
                        {% for follower in profile_user.followers.all %}
                            <li class="list-group-item d-flex justify-content-between align-items-center">
                                <a href="{% url 'accounts:public_profile' follower.nickname %}">
                                    {{ follower.nickname }}
                                </a>

                                {% if user.is_authenticated and user != follower and follower not in user.following.all %}
                                    <form action="{% url 'accounts:toggle_follow' follower.nickname %}"
                                          method="post"
                                          class="ajax-follow-toggle ajax-follow-reload d-inline">
                                        {% csrf_token %}
                                        <button type="submit"
                                                class="btn btn-sm {% if follower in request.user.following.all %}btn-primary{% else %}btn-outline-primary{% endif %}">
                                            {% if follower in request.user.following.all %}Отписаться{% else %}
                                                Подписаться{% endif %}
                                        </button>
                                    </form>
                                {% endif %}
                            </li>
                        {% empty %}
                            <li class="list-group-item text-muted">Нет подписчиков</li>
                        {% endfor %}
                    </ul>
                </div>
            </div>

            <div class="col-md-6">
                <div class="card mb-3">
                    <div class="card-header">
                        Подписки ({{ following_count }})
                    </div>
                    <ul class="list-group list-group-flush">
                        {% for following in profile_user.following.all %}
                            <li class="list-group-item d-flex justify-content-between align-items-center">
                                <a href="{% url 'accounts:public_profile' following.nickname %}">
                                    {{ following.nickname }}
                                </a>
                                {% if user.is_authenticated and user == profile_user %}
                                    <form action="{% url 'accounts:toggle_follow' following.nickname %}"
                                          method="post"
                                          class="ajax-follow-toggle ajax-follow-reload d-inline">
                                        {% csrf_token %}
                                        <button type="submit"
                                                class="btn btn-sm {% if following in user.following.all %}btn-primary{% else %}btn-outline-primary{% endif %}">
                                            {% if following in user.following.all %}Отписаться{% else %}
                                                Подписаться{% endif %}
                                        </button>
                                    </form>
                                {% endif %}
                            </li>
                        {% empty %}
                            <li class="list-group-item text-muted">Ни на кого не подписан</li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
        </div>


        <hr>
        <h4>Посты</h4>
        {% for post in posts %}
            <div class="card mb-3">
                <div class="card-header text-muted d-flex flex-column flex-sm-row justify-content-between gap-2">
                    <h5>{{ post.title }}</h5>
                    <small class="text-muted">Опубликовано: {{ post.created_at|date:"d.m.Y H:i" }}</small>
                </div>
                <div class="card-body">
                    <p>{{ post.content|truncatewords:30 }}</p>
                </div>
                <div class="card-footer">
                    <div class="d-flex flex-column flex-sm-row justify-content-left gap-1">
                        {% if user|can_interact %}
                            <form class="like-form" data-post-id="{{ post.pk }}" method="post"
                                  action="{% url 'social:post_like_toggle' post.pk %}">
                                {% csrf_token %}
                                <button type="submit"
                                        class="like-button btn btn-sm {% if user in post.likes.all %}btn-danger{% else %}btn-outline-danger{% endif %}">
                                    ❤ <span class="like-count">{{ post.likes.count }}</span>
                                </button>
                            </form>
                        {% else %}
                            ❤ {{ post.likes.count }}
                        {% endif %}
                        &nbsp;&nbsp; 💬 {{ post.comments.count }}&nbsp;&nbsp;&nbsp;&nbsp;
                        <div>
                            <a href="{% url 'social:post_detail' post.pk %}" class="btn btn-sm btn-outline-primary">Подробнее</a>
                        </div>
                    </div>
                </div>
            </div>
        {% empty %}
            <p>Нет опубликованных постов.</p>
        {% endfor %}
    </div>
{% endblock %}