MiniSocial_Project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('accounts/', include(('accounts.urls', 'accounts'), namespace='accounts')),
    path('', include('core.urls'), name='core'),
    path('', include('social.urls'), name='social'),
    path('notifications/', include('notifications.urls'), name='notifications'),
    path('messaging/', include('messaging.urls'), name='messaging'),
    path('requests/', include('requests.urls'), name='requests'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path, reverse_lazy
from . import views

app_name = 'accounts'

urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('register/', views.register_view, name='register'),
    path('profile/', views.profile_view, name='profile'),
    path('profile/edit/', views.profile_edit_view, name='profile_edit'),
    path('password/change/', views.password_change_view, name='password_change'),
    path('users/', views.user_list, name='user_list'),
    path('users/<str:nickname>/', views.public_profile, name='public_profile'),
    path('users/<str:nickname>/follow/', views.toggle_follow, name='toggle_follow'),
    path('password_reset/',
         auth_views.PasswordResetView.as_view(
             template_name='accounts/password_reset_form.html',
             email_template_name='accounts/password_reset_email.html',
             success_url=reverse_lazy('accounts:password_reset_done')  # ✅ явно указано с namespace
         ),
         name='password_reset'
         ),
    path('password_reset/done/',
         auth_views.PasswordResetDoneView.as_view(template_name='accounts/password_reset_done.html',
                                                  ),
         name='password_reset_done'),
    path('reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name='accounts/password_reset_confirm.html',
                                                     success_url=reverse_lazy('accounts:password_reset_complete'), ),
         name='password_reset_confirm'),
    path('reset/done/',
         auth_views.PasswordResetCompleteView.as_view(template_name='accounts/password_reset_complete.html'),
         name='password_reset_complete'),
    path('confirm-email/<uidb64>/<token>/', views.confirm_email, name='confirm_email'),
    path('resend_activation/', views.resend_activation_email, name='resend_activation'),
    path('settings/', views.edit_user_settings, name='edit_user_settings'),

]

core/urls.py
from django.urls import path
from . import views

app_name = 'core'

urlpatterns = [
    path('', views.home, name='home'),
]

social/urls.py
#social/urls.py
from django.urls import path
from . import views

app_name = 'social'

urlpatterns = [
    path('posts/', views.post_list, name='post_list'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<int:pk>/edit/', views.post_edit, name='post_edit'),
    path('<int:pk>/', views.post_detail, name='post_detail'),
    path('posts/<int:post_id>/delete/', views.post_delete, name='post_delete'),
    path('<int:pk>/like/', views.post_like_toggle, name='post_like_toggle'),
    path('comments/<int:comment_id>/delete/', views.comment_delete, name='comment_delete'),
]

social/models.py
#social/models.py
from django.conf import settings
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType
from django.db import models
from django.db.models import Q, UniqueConstraint



from social.managers import PostManager


def post_image_path(instance, filename):
    return f'posts/user_{instance.author.id}/{filename}'


class Post(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True, blank=True, related_name='posts')
    title = models.CharField("Заголовок", max_length=200)
    content = models.TextField(max_length=1000)
    image = models.ImageField(upload_to=post_image_path, blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    likes = models.ManyToManyField(
        settings.AUTH_USER_MODEL,
        related_name='liked_posts',
        blank=True
    )
    objects = PostManager()
    class Meta:
        ordering = ['-created_at']

    def __str__(self):
        return f"{self.title} — {self.author.nickname}"
        # return f'{self.author.username}: {self.content[:30]}...'

    def get_absolute_url(self):
        return f'/{self.id}/'

    def comments_count(self):
        return self.comments.count()

    def likes_count(self):
        return self.likes.count()

class Comment(models.Model):
    post = models.ForeignKey('Post', on_delete=models.CASCADE, related_name='comments')
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='comments')
    content = models.TextField('Комментарий')
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-created_at']

    def __str__(self):
        return f"Комментарий от {self.author or 'Аноним'} к посту {self.post_id}"

    def get_absolute_url(self):
        return f'/{self.post_id}/#comment-{self.id}'

# class Notification(models.Model):
#     NOTIFICATION_TYPES = [
#         ('like', 'Лайк'),
#         ('comment', 'Комментарий'),
#         ('follow', 'Подписка'),
#     ]
#
#     recipient = models.ForeignKey(
#         settings.AUTH_USER_MODEL,
#         on_delete=models.CASCADE,
#         related_name='notifications'
#     )
#     actor = models.ForeignKey(
#         settings.AUTH_USER_MODEL,
#         on_delete=models.CASCADE,
#         related_name='actor_notifications'
#     )
#     verb = models.CharField(max_length=20, choices=NOTIFICATION_TYPES)
#     created_at = models.DateTimeField(auto_now_add=True)
#     is_read = models.BooleanField(default=False)
#
#     # Для связи с объектом (например, постом или комментарием)
#     content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE, null=True, blank=True)
#     object_id = models.PositiveIntegerField(null=True, blank=True)
#     target = GenericForeignKey('content_type', 'object_id')
#
#     class Meta:
#         constraints = [
#             UniqueConstraint(
#                 fields=['actor', 'recipient', 'verb', 'content_type', 'object_id'],
#                 condition=Q(verb='like'),
#                 name='unique_like_notification'
#             ),
#         ]
#
#     def __str__(self):
#         return f'{self.actor} -> {self.recipient}: {self.verb}'
#

social/forms.py
from django import forms
from .models import Post, Comment


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title','content', 'image']
        widgets = {
            'content': forms.Textarea(attrs={
                'class': 'form-control',
                'rows': 4,
                'placeholder': 'Что у вас нового?'
            }),
            'image': forms.ClearableFileInput(attrs={'class': 'form-control'}),
        }

# class CommentForm(forms.ModelForm):
#     class Meta:
#         model = Comment
#         fields = ['content']
#         widgets = {
#             'content': forms.Textarea(attrs={
#                 'class': 'form-control',
#                 'rows': 2,
#                 'placeholder': 'Оставьте комментарий...'
#             }),
#         }

class CommentForm(forms.ModelForm):
    content = forms.CharField(
        label='Комментарий',
        widget=forms.Textarea(attrs={
            'rows': 2,
            'placeholder': 'Напишите комментарий...',
            'class': 'form-control',
        })
    )

    class Meta:
        model = Comment
        fields = ['content']

social/views.py
#social/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.db.models import Q, Count
from django.http import HttpResponseRedirect, JsonResponse
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse
from django.utils import timezone

from .forms import PostForm, CommentForm
from .models import Post,  Comment

from utils.settings import get_user_settings
from utils.notifications import create_notification
from utils.templatetags.rights import can_edit_post, can_delete_comment, can_delete_post



@login_required
def post_create(request):
    form = PostForm(request.POST or None, request.FILES or None)
    if form.is_valid():
        post = form.save(commit=False)
        post.author = request.user
        post.save()
        return redirect('social:post_list')
    return render(request, 'social/post_form.html', {'form': form})


@login_required
def post_edit(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if post.author != request.user or not can_edit_post(post, request.user):
        return redirect('social:post_list')

    form = PostForm(request.POST or None, request.FILES or None, instance=post)
    if form.is_valid():
        form.save()
        return redirect('social:post_list')
    return render(request, 'social/post_form.html', {'form': form, 'edit': True, 'post': post})

#@login_required
def post_list(request):

    posts = Post.objects.select_related('author').prefetch_related('comments', 'likes')
    query = ''
    filter_type = ''
    sort_by = ''


    if request.user.is_authenticated:
        query = request.GET.get('q', '')
        filter_type = request.GET.get('filter')
        sort_by = request.GET.get('sort', '-created_at')

        if filter_type == 'following':
            posts = posts.filter(author__in=request.user.following.all())
        elif filter_type == 'not_following':
            posts = posts.exclude(Q(author__in=request.user.following.all()) | Q(author=request.user))
        elif filter_type == 'followers':
            posts = posts.filter(author__in=request.user.followers.all())

        if query:
            posts = posts.filter(
                Q(title__icontains=query) |
                Q(content__icontains=query) |
                Q(author__nickname__icontains=query)
            )
    else:
        sort_by = request.GET.get('sort', '-created_at')

    allowed_sorts = {
        'date_new': '-created_at',
        'date_old': 'created_at',
        'likes': '-likes_count',
        'comments': '-comments_count',
    }
    if sort_by not in allowed_sorts.values():
        sort_by = '-created_at'

    # if 'likes_count' in sort_by or 'comments_count' in sort_by:
    #     posts = posts.annotate(
    #         comments_count=Count('comments', distinct=True),
    #         likes_count=Count('likes', distinct=True)
    #     )

    posts = posts.order_by(sort_by)
    posts_per_page = get_user_settings( ['POSTS_PER_PAGE'],request.user).get('POSTS_PER_PAGE', 10)
    paginator = Paginator(posts, posts_per_page)  # по 10 пользователей на страницу
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    return render(request, 'social/post_list.html', {
        'page_obj': page_obj,
        'query': query,
        'filter_type': filter_type,
        'sort_by': sort_by
    })


@login_required
def post_detail(request, pk):
    post = get_object_or_404(Post, pk=pk)
    comments = post.comments.select_related('author')
    form = CommentForm(request.POST or None)
    posts_per_page = get_user_settings(['POSTS_PER_PAGE'], request.user).get('POSTS_PER_PAGE', 10)
    paginator = Paginator(comments, posts_per_page)  # по 10 пользователей на страницу
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    if request.method == 'POST' and form.is_valid():
        comment = form.save(commit=False)
        comment.post = post
        comment.author = request.user
        comment.save()
        create_notification(actor=request.user, recipient=post.author, verb='comment', target=comment)
        return redirect('social:post_detail', pk=pk)
    return render(request, 'social/post_detail.html', {
        'post': post,
        'page_obj': page_obj,
        'form': form
    })

@login_required
def post_delete(request, post_id):
    post = get_object_or_404(Post, id=post_id)

    if not can_delete_post(post,request.user):
        messages.error(request, "Вы не можете удалить этот пост.")
        return redirect('social:post_edit', pk=post.id)

    post.delete()
    messages.success(request, "Пост успешно удалён.")
    return redirect('social:post_list')

@login_required
def post_like_toggle(request, pk):
    post = get_object_or_404(Post, id=pk)
    user = request.user

    if user in post.likes.all():
        post.likes.remove(user)
        liked = False
    else:
        post.likes.add(user)
        liked = True
        create_notification(actor=user, recipient=post.author, verb='like', target=post)

    if request.headers.get('x-requested-with') == 'XMLHttpRequest':
        return JsonResponse({
            'liked': liked,
            'likes_count': post.likes.count(),
        })

    next_url = request.POST.get('next') or request.META.get('HTTP_REFERER') or '/'
    return redirect(next_url)

@login_required
def comment_delete(request, comment_id):
    comment = get_object_or_404(Comment, id=comment_id)

    if not can_delete_comment(comment, request.user):
        messages.error(request, "Вы не можете удалить этот комментарий.")
        return redirect('social:post_detail', pk=comment.post.id)

    comment.delete()
    messages.success(request, "Комментарий удалён.")
    return redirect('social:post_detail', pk=comment.post.id)

# @login_required
# def notification_list(request):
#     notifications = request.user.notifications.all().order_by('-created_at')
#     return render(request, 'social/notification_list.html', {'notifications': notifications})

social/templates/social/post_detail.html
{% extends 'base.html' %}
{% load rights %}
{% block title %}Пост{% endblock %}
{% block content %}
    <div class="container mt-4">
        <div class="card mb-4">
            <div class="card-header">
                <strong>
                    {% if post.author %}
                        Автор:
                        <a href="{% url 'accounts:public_profile' post.author.nickname %}">{{ post.author.nickname }}</a>
                    {% else %}
                        <span class="text-muted">Автор удалён</span>
                    {% endif %}
                </strong> —
                {{ post.created_at|date:"d.m.Y H:i" }}
            </div>
            <div class="card-body gap-2">
                <p>{{ post.content|linebreaks }}</p>
                {% if post.image %}
                    <img src="{{ post.image.url }}" class="img-fluid rounded">
                {% endif %}
            </div>
            <div class="card-footer">
                {% if user|can_interact %}
                    <form class="like-form" data-post-id="{{ post.pk }}" method="post"
                          action="{% url 'social:post_like_toggle' post.pk %}">
                        {% csrf_token %}
                        <button type="submit"
                                class="like-button btn btn-sm {% if user in post.likes.all %}btn-danger{% else %}btn-outline-danger{% endif %}">
                            ❤ <span class="like-count">{{ post.likes.count }}</span>
                        </button>
                    </form>
                {% else %}
                    ❤ {{ post.likes.count }}
                {% endif %}
            </div>


        </div>
        <h3>Комментарии</h3>

        {% for comment in page_obj %}
            <div id="comment-{{ comment.id }}" class="mb-2 border p-3 rounded bg-light">
                <div class="d-flex justify-content-between align-items-start">
                    <div>
                        <strong>{{ comment.author.nickname }}</strong> —
                        <small>{{ comment.created_at|date:"d.m.Y H:i" }}</small>
                    </div>
                    {% if comment|can_delete_comment:user %}
                        <button
                                class="btn btn-sm btn-outline-danger"
                                data-bs-toggle="modal"
                                data-bs-target="#confirmDeleteModal"
                                data-delete-url="{% url 'social:comment_delete' comment.id %}"
                        >
                            <i class="bi bi-trash"></i>
                        </button>
                    {% endif %}
                </div>
                <p class="mt-2 mb-0">{{ comment.content|linebreaks }}</p>
            </div>
        {% empty %}
            <p>Пока нет комментариев.</p>
        {% endfor %}
        <nav>
            <ul class="pagination justify-content-center mt-3">
                {% if page_obj.has_previous %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ page_obj.previous_page_number }}">Назад</a>
                    </li>
                {% endif %}

                <li class="page-item disabled">
                    <span class="page-link">Страница {{ page_obj.number }} из {{ page_obj.paginator.num_pages }}</span>
                </li>

                {% if page_obj.has_next %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ page_obj.next_page_number }}">Вперёд</a>
                    </li>
                {% endif %}
            </ul>
        </nav>

        {% if user.is_authenticated %}
            {% if user|can_interact %}
                <form method="post">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-primary btn-sm">Оставить комментарий</button>
                </form>
            {% else %}
                <div class="alert alert-warning mt-3">
                    {{ user|get_interaction_restriction_reason }}
                </div>
            {% endif %}
        {% else %}
            <p><a href="{% url 'login' %}">Войдите</a>, чтобы оставить комментарий.</p>
        {% endif %}

    </div>

{% endblock %}

social/templates/social/post_form.html
{% extends 'base.html' %}
{% load rights %}
{% block title %}{% if edit %}Редактировать пост{% else %}Новый пост{% endif %}{% endblock %}
{% block content %}
    <div class="container mt-4">
        <h3>{% if edit %}Редактировать пост{% else %}Создать пост{% endif %}</h3>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-success">Сохранить</button>
            <a href="{% url 'social:post_list' %}" class="btn btn-secondary">Отмена</a>
            {% if post|can_delete_post:user %}
                <button type="button"
                        class="btn btn-sm btn-outline-danger"
                        data-bs-toggle="modal"
                        data-bs-target="#confirmDeleteModal"
                        data-delete-url="{% url 'social:post_delete' post.id %}"
                >
                    <i class="bi bi-trash"></i> Удалить пост
                </button>
        </form>
            {% endif %}

    </div>
{% endblock %}

social/templates/social/post_list.html
{% extends 'base.html' %}
{% load rights %}
{% block title %}Лента постов{% endblock %}
{% block content %}
<div class="container mt-4">
    <h3 class="mb-4">Лента постов</h3>
    {% if user|can_interact %}
    <a href="{% url 'social:post_create' %}" class="btn btn-primary mb-3">Создать пост</a>
    <form method="get" class="mb-3 d-flex" role="search">
        <input type="hidden" name="filter" value="{{ filter_type }}">
        <input type="hidden" name="sort" value="{{ sort_by }}">
        <input type="text" name="q" value="{{ query }}" class="form-control me-2"
               placeholder="Поиск по постам...">
        <button class="btn btn-outline-primary" type="submit">Поиск</button>
    </form>
    <div class="text-muted d-flex flex-column flex-sm-row justify-content-between gap-2">
        <div>
            <div class="mb-3">
                <a href="?filter=all&q={{ query }}&sort={{ sort_by }}" class="btn btn-sm btn-outline-secondary">Все</a>
                <a href="?filter=following&q={{ query }}&sort={{ sort_by }}" class="btn btn-sm btn-outline-primary">Только
                    подписки</a>
                <a href="?filter=not_following&q={{ query }}&sort={{ sort_by }}" class="btn btn-sm btn-outline-warning">Кого
                    не читаю</a>
                <a href="?filter=followers&q={{ query }}&sort={{ sort_by }}" class="btn btn-sm btn-outline-success">Кто
                    читает меня</a>
            </div>
        </div>
        <div>
            <div class="mb-3">
                <span>Сортировка:</span>
                <a href="?filter={{ filter_type }}&q={{ query }}&sort=-created_at"
                   class="btn btn-sm btn-outline-secondary">Новые</a>
                <a href="?filter={{ filter_type }}&q={{ query }}&sort=created_at"
                   class="btn btn-sm btn-outline-secondary">Старые</a>
                <a href="?filter={{ filter_type }}&q={{ query }}&sort=-likes_count"
                   class="btn btn-sm btn-outline-secondary">По лайкам</a>
                <a href="?filter={{ filter_type }}&q={{ query }}&sort=-comments_count"
                   class="btn btn-sm btn-outline-secondary">По комментариям</a>
            </div>
        </div>
    </div>
    {% endif %}
    {% for post in page_obj %}
    <div id="post-{{ post.id }}" class="card mb-3">
        <div class="card-header d-flex justify-content-between">
            <h5>{{ post.title }}</h5>
            <small class="text-muted">{{ post.created_at|date:"d.m.Y H:i" }}</small>
        </div>
        <div class="card-body">
            <p class="card-text">{{ post.content|truncatechars:200 }}</p>
            {% if post.image %}
            <img src="{{ post.image.url }}" class="img-fluid rounded d-block mx-auto my-3" alt=""
                 Изображение к посту #{{ post.id }}{% if post.author %} пользователя {{ post.author.nickname }}{%endif %}">
            {% endif %}
        </div>
        <div class="card-footer text-muted d-flex flex-column flex-sm-row justify-content-between gap-2">
            <div class="d-flex flex-column flex-sm-row justify-content-between gap-1">
                {% if user|can_interact %}
                <form class="like-form" data-post-id="{{ post.pk }}" method="post"
                      action="{% url 'social:post_like_toggle' post.pk %}">
                    {% csrf_token %}
                    <button type="submit"
                            class="like-button btn btn-sm {% if user in post.likes.all %}btn-danger{% else %}btn-outline-danger{% endif %}">
                        ❤ <span class="like-count">{{ post.likes.count }}</span>
                    </button>
                </form>
                {% else %}
                ❤ {{ post.likes.count }}
                {% endif %}
                &nbsp;&nbsp; 💬 {{ post.comments.count }}&nbsp;&nbsp;&nbsp;&nbsp;
                <div>
                    <a href="{% url 'social:post_detail' post.pk %}"
                       class="btn btn-sm btn-outline-primary">Подробнее</a>
                </div>
                {% if post|can_edit_post:user %}
                <div>
                    <a href="{% url 'social:post_edit' post.pk %}" class="btn btn-sm btn-outline-secondary">Редактировать</a>
                </div>
                {% endif %}
            </div>
            <div>
                {% if post.author %}
                Автор:
                <a href="{% url 'accounts:public_profile' post.author.nickname %}">{{ post.author.nickname }}</a>
                {% else %}
                <span class="text-muted">Автор удалён</span>
                {% endif %}
            </div>
        </div>
    </div>
    {% empty %}
    <p>Постов пока нет.</p>
    {% endfor %}
    <nav>
        <ul class="pagination justify-content-center mt-3">
            {% if page_obj.has_previous %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.previous_page_number }}">Назад</a>
            </li>
            {% endif %}

            <li class="page-item disabled">
                <span class="page-link">Страница {{ page_obj.number }} из {{ page_obj.paginator.num_pages }}</span>
            </li>

            {% if page_obj.has_next %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.next_page_number }}">Вперёд</a>
            </li>
            {% endif %}
        </ul>
    </nav>

</div>
{% endblock %}